export type Emotion = 'happy' | 'sad' | 'excited' | 'scared' | 'romantic' | 'inspired' | 'amused' | 'intrigued' | 'enthusiastic' | 'melancholic' | 'tender' | 'suspenseful' | 'adventurous' | 'disappointed' | 'shocked' | 'comforted' | 'annoyed' | 'wonderstruck' | 'calm' | 'moved';
export const allEmotions: Emotion[] = [
  'happy',
  'sad',
  'excited',
  'scared',
  'romantic',
  'inspired',
  'amused',
  'intrigued',
  'enthusiastic',
  'melancholic',
  'tender',
  'suspenseful',
  'adventurous',
  'disappointed',
  'shocked',
  'comforted',
  'annoyed',
  'wonderstruck',
  'calm',
  'moved',
];